### ISSUE TITLE
Finding ballance wallet

### ISSUE THREAD

**Issue by igooorrr** [Pymmdrza/Pyromid#11]
Where can I find wallets with balance, if i brute them?

**Comment by Pymmdrza** [comment]
> Where can I find wallets with balance, if i brute them?

https://github.com/Pymmdrza/Rich-Address-Wallet

**Comment by igooorrr** [comment]
I meant if ur program finds wallet with balance, where can i find this wallet and key for it

**Comment by Pymmdrza** [comment]
> I meant if ur program finds wallet with balance, where can i find this wallet and key for it

It's like you still don't know what you want??? The [list of valuable wallets (Rich)](https://github.com/Pymmdrza/Rich-Address-Wallet 'Rich Address Wallet List') is required in all my softwares that are built in the field. But I don't think you have any knowledge about this field, and I recommend you not to use my software because you can't do anything with them. (* **You don't even know what the private key of the wallet is, so you come here to ask me for such a thing**)
